### ISSUE TITLE
TRYing since 2 days To load  the NODE Pulid-ComfyUI , using MANAGER and ITS ' impossible = > 

### ISSUE THREAD

**Issue by ABIA2024** [cubiq/PuLID_ComfyUI#120]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
LOG:
Cannot import C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI module for custom nodes: No module named 'insightface'

[rgthree-comfy] Loaded 42 magnificent nodes. 🎉

Import times for custom nodes:
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds (IMPORT FAILED): C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_LLM
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\EchoMimicV2-ComfyUI
   0.1 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tensorops
   0.3 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence-2
   1.2 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic
   1.5 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]

![screenshot 665](https://github.com/user-attachments/assets/a0dae929-a1b5-453f-928d-babcfd6f8642)

**Comment by ABIA2024** [comment]
new tentative with more information, maybe if tha can help (pb with insightface ?)
## Execute install/(de)activation script for 'C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI'
 Ignoring onnxruntime-gpu: markers 'sys_platform != "darwin" and platform_machine == "x86_64"' don't match your environment

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
  32.9 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 65469 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\web
Successfully imported omost_function from omost.py in the current directory
Successfully imported omost_function from omost.py in the current directory
### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Revision: 2909 [fd5dfb81] *DETACHED | Released on '2024-12-12'
C:\Comfyui\ComfyUI_windows_portable
############################################
C:\Comfyui\ComfyUI_windows_portable\custom_nodes\ComfyUI-NAI-styler\CSV
############################################
[]
############################################
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[tinyterraNodes] Loaded
Traceback (most recent call last):
  File "C:\Comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI\__init__.py", line 1, in <module>
    from .pulid import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI\pulid.py", line 9, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

Cannot import C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI module for custom nodes: No module named 'insightface'

[rgthree-comfy] Loaded 42 exciting nodes. 🎉


Import times for custom nodes:
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_LLM
   0.0 seconds (IMPORT FAILED): C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\EchoMimicV2-ComfyUI
   0.1 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tensorops
   0.3 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence-2
   1.1 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic
   1.5 seconds: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Comfyui\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
