### ISSUE TITLE
PuLID won't install

### ISSUE THREAD

**Issue by Vektor369** [cubiq/PuLID_ComfyUI#123]
I had this working before. Not sure what happened. Couldn't get it installed, so I got a fresh install of ComfyUI. Still won't install. After I try, I get this in the console:
```

F:\AI\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-17 15:59:31.893417
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI
** Log path: F:\AI\ComfyUI\ComfyUI_windows_portable\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['F:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'facexlib']

## Execute install/(de)activation script for 'F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI'
 Collecting facexlib
   Using cached facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)
 Collecting filterpy (from facexlib)
   Using cached filterpy-1.4.5-py3-none-any.whl
 Collecting numba (from facexlib)
   Using cached numba-0.60.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
  Collecting opencv-python (from facexlib)
   Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
      Collecting matplotlib (from filterpy->facexlib)
   Downloading matplotlib-3.10.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
 Collecting llvmlite<0.44,>=0.43.0dev0 (from numba->facexlib)
   Using cached llvmlite-0.43.0-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
           Collecting contourpy>=1.0.1 (from matplotlib->filterpy->facexlib)
   Using cached contourpy-1.3.1-cp312-cp312-win_amd64.whl.metadata (5.4 kB)
 Collecting cycler>=0.10 (from matplotlib->filterpy->facexlib)
   Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
 Collecting fonttools>=4.22.0 (from matplotlib->filterpy->facexlib)
   Using cached fonttools-4.55.3-cp312-cp312-win_amd64.whl.metadata (168 kB)
 Collecting kiwisolver>=1.3.1 (from matplotlib->filterpy->facexlib)
   Using cached kiwisolver-1.4.7-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
  Collecting pyparsing>=2.3.1 (from matplotlib->filterpy->facexlib)
   Using cached pyparsing-3.2.0-py3-none-any.whl.metadata (5.0 kB)
 Collecting python-dateutil>=2.7 (from matplotlib->filterpy->facexlib)
   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
 Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib->filterpy->facexlib)
   Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
 Using cached facexlib-0.3.0-py3-none-any.whl (59 kB)
 Using cached numba-0.60.0-cp312-cp312-win_amd64.whl (2.7 MB)
 Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)
 Using cached llvmlite-0.43.0-cp312-cp312-win_amd64.whl (28.1 MB)
 Downloading matplotlib-3.10.0-cp312-cp312-win_amd64.whl (8.0 MB)
    ---------------------------------------- 8.0/8.0 MB 10.0 MB/s eta 0:00:00
 Using cached contourpy-1.3.1-cp312-cp312-win_amd64.whl (220 kB)
 Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
 Using cached fonttools-4.55.3-cp312-cp312-win_amd64.whl (2.2 MB)
 Using cached kiwisolver-1.4.7-cp312-cp312-win_amd64.whl (55 kB)
 Using cached pyparsing-3.2.0-py3-none-any.whl (106 kB)
 Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
 Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
 Installing collected packages: six, pyparsing, opencv-python, llvmlite, kiwisolver, fonttools, cycler, contourpy, python-dateutil, numba, matplotlib, filterpy, facexlib
[!]   WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
[!]   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
 Successfully installed contourpy-1.3.1 cycler-0.12.1 facexlib-0.3.0 filterpy-1.4.5 fonttools-4.55.3 kiwisolver-1.4.7 llvmlite-0.43.0 matplotlib-3.10.0 numba-0.60.0 opencv-python-4.10.0.84 pyparsing-3.2.0 python-dateutil-2.9.0.post0 six-1.17.0

## ComfyUI-Manager: EXECUTE => ['F:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'insightface']

## Execute install/(de)activation script for 'F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI'
 Collecting insightface
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=[])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
[!]       self.run_setup()
[!]     File "F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
install/(de)activation script failed: F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI

## ComfyUI-Manager: EXECUTE => ['F:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'onnxruntime']

## Execute install/(de)activation script for 'F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI'
 Collecting onnxruntime
   Using cached onnxruntime-1.20.1-cp312-cp312-win_amd64.whl.metadata (4.7 kB)
 Collecting coloredlogs (from onnxruntime)
   Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
 Collecting flatbuffers (from onnxruntime)
   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
   Collecting protobuf (from onnxruntime)
   Using cached protobuf-5.29.1-cp310-abi3-win_amd64.whl.metadata (592 bytes)
  Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime)
   Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
  Collecting pyreadline3 (from humanfriendly>=9.1->coloredlogs->onnxruntime)
   Using cached pyreadline3-3.5.4-py3-none-any.whl.metadata (4.7 kB)
 Using cached onnxruntime-1.20.1-cp312-cp312-win_amd64.whl (11.3 MB)
 Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
 Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
 Using cached protobuf-5.29.1-cp310-abi3-win_amd64.whl (434 kB)
 Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
 Using cached pyreadline3-3.5.4-py3-none-any.whl (83 kB)
 Installing collected packages: flatbuffers, pyreadline3, protobuf, humanfriendly, coloredlogs, onnxruntime
[!]   WARNING: The script humanfriendly.exe is installed in 'F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
[!]   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
[!]   WARNING: The script coloredlogs.exe is installed in 'F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
[!]   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
[!]   WARNING: The script onnxruntime_test.exe is installed in 'F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
[!]   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
 Successfully installed coloredlogs-15.0.1 flatbuffers-24.3.25 humanfriendly-10.0 onnxruntime-1.20.1 protobuf-5.29.1 pyreadline3-3.5.4

## ComfyUI-Manager: EXECUTE => ['F:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', "onnxruntime-gpu; sys_platform != 'darwin' and platform_machine == 'x86_64'"]

## Execute install/(de)activation script for 'F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI'
 Ignoring onnxruntime-gpu: markers 'sys_platform != "darwin" and platform_machine == "x86_64"' don't match your environment

## ComfyUI-Manager: EXECUTE => ['F:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'ftfy']

## Execute install/(de)activation script for 'F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI'
 Collecting ftfy
   Using cached ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
 Collecting wcwidth (from ftfy)
   Using cached wcwidth-0.2.13-py2.py3-none-any.whl.metadata (14 kB)
 Using cached ftfy-6.3.1-py3-none-any.whl (44 kB)
 Using cached wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
 Installing collected packages: wcwidth, ftfy
[!]   WARNING: The script ftfy.exe is installed in 'F:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
[!]   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
 Successfully installed ftfy-6.3.1 wcwidth-0.2.13

## ComfyUI-Manager: EXECUTE => ['F:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'timm']

## Execute install/(de)activation script for 'F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI'
 Collecting timm
   Using cached timm-1.0.12-py3-none-any.whl.metadata (51 kB)
                         Using cached timm-1.0.12-py3-none-any.whl (2.4 MB)
 Installing collected packages: timm
 Successfully installed timm-1.0.12

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
  47.6 seconds: F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32648 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path custom_nodes F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\tests\inference\testing_nodes
Adding extra search path checkpoints F:\AI\ComfyUI\models/checkpoints/
Adding extra search path clip F:\AI\ComfyUI\models/clip/
Adding extra search path clip_vision F:\AI\ComfyUI\models/clip_vision/
Adding extra search path configs F:\AI\ComfyUI\models/configs/
Adding extra search path vae F:\AI\ComfyUI\models/vae/
Adding extra search path loras F:\AI\ComfyUI\models/loras/
Adding extra search path diffusion_models F:\AI\ComfyUI\models\Stable-diffusion\Flux
Adding extra search path upscale_models F:\AI\ComfyUI\models/upscale_models/
Adding extra search path embeddings F:\AI\ComfyUI\models/embeddings/
Adding extra search path hypernetworks F:\AI\ComfyUI\models/hypernetworks
Adding extra search path controlnet F:\AI\ComfyUI\models/controlnet/
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Revision: 2890 [9a616b81] *DETACHED | Released on '2024-12-04'
Traceback (most recent call last):
  File "F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2037, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI\__init__.py", line 1, in <module>
    from .pulid import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI\pulid.py", line 9, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

Cannot import F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI module for custom nodes: No module named 'insightface'

Import times for custom nodes:
   0.0 seconds: F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\tests\inference\testing_nodes\testing-pack
   0.0 seconds (IMPORT FAILED): F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.3 seconds: F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: F:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

Any help would be appreciated. Thanks in advance.

**Comment by sweihub** [comment]
I finally find out I should clone the code to `ComfyUI/custom_nodes`, would you document it dear author?
