### ISSUE TITLE
IPAdapter Issue

### ISSUE THREAD

**Issue by Marcusstory79** [cubiq/PuLID_ComfyUI#25]
Everytime it gets to the IP Adapter in the workflow, it crashes with this error !!! Exception during processing!!! 'Attn2Replace' object has no attribute 'set_new_condition'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 696, in apply_ipadapter
    work_model, face_image = ipadapter_execute(work_model, ipadapter_model, clip_vision, **ipa_args)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 392, in ipadapter_execute
    set_model_patch_replace(model, patch_kwargs, ("input", id, index))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 146, in set_model_patch_replace
    to["patches_replace"]["attn2"][key].set_new_condition(**patch_kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Attn2Replace' object has no attribute 'set_new_condition'
<img width="1136" alt="Screenshot 2024-05-13 165754" src="https://github.com/cubiq/PuLID_ComfyUI/assets/148150405/8ba5b00b-ae3a-478d-a06f-9ebed5f98e82">

**Comment by cubiq** [comment]
upgrade ipadapter
