### ISSUE TITLE
Error occurred when executing PulidInsightFaceLoader

### ISSUE THREAD

**Issue by MrsHorrid** [cubiq/PuLID_ComfyUI#27]
File "D:\comfyushit\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\comfyushit\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\comfyushit\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\comfyushit\ComfyUI\custom_nodes\PuLID_ComfyUI\pulid.py", line 237, in load_insightface
model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
File "D:\comfyushit\ComfyUI\venv\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
assert 'detection' in self.models

**Comment by maxadc** [comment]
So am I.

**Comment by cubiq** [comment]
do you get any error at startup?

**Comment by jagdd** [comment]
> 启动时出现任何错误吗？

全部节点显示正常执行PulidInsightFaceLoader这个节点!! Exception during processing!!! 'PulidInsightFaceLoader' object has no attribute 'load_insightface'
Traceback (most recent call last):
  File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^
AttributeError: 'PulidInsightFaceLoader' object has no attribute 'load_insightface'

Prompt executed in 18.36 seconds

**Comment by jagdd** [comment]
![Uploading 33e96e7e8ceee97b885dd1f00cbf7b5.png…]()

**Comment by apon** [comment]
So am I. The reason is that after antelopev2.zip is decompressed, the path becomes 'antelopev2\antelopev2'.

**Comment by aayan5555** [comment]
> So am I. The reason is that after antelopev2.zip is decompressed, the path becomes 'antelopev2\antelopev2'.

Thanks this fixed the error:
Copy every thing from \antelopev2\antelopev2' \to antelopev2 ( one folder up)

**Comment by MaxCastella** [comment]
I had the same problem and it worked. The full path is (...)\ComfyUI\models\insightface\models\antelopev2
