### ISSUE TITLE
ApplyPulidFlux <urlopen error [Errno 110] Connection timed out>

### ISSUE THREAD

**Issue by currenttime** [cubiq/PuLID_ComfyUI#85]
![微信截图_20241008160142](https://github.com/user-attachments/assets/68b72256-b98a-41d0-a19b-6fc57db1707a)

Information:
OS: Ubuntu 22.04
Conda Environment: python=3.10

024-10-08 06:17:12,277 - root - INFO - To see the GUI go to: http://0.0.0.0:8188
2024-10-08 06:47:06,322 - root - INFO - got prompt
2024-10-08 06:47:06,333 - root - ERROR - Failed to validate prompt for output 50:
2024-10-08 06:47:06,334 - root - ERROR - * DualCLIPLoader 64:
2024-10-08 06:47:06,334 - root - ERROR -   - Value not in list: clip_name1: 't5xxl_fp16.safetensors' not in ['EVA02_CLIP_L_336_psz14_s6B.pt', 'ViT-L-14-BEST-smooth-GmP-TE-only-HF-format.safetensors', 'ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors', 'clip_g.safetensors', 'clip_l.safetensors', 'siglip-so400m-patch14-384/model.safetensors', 't5xxl_fp8_e4m3fn.safetensors']
2024-10-08 06:47:06,334 - root - ERROR - Output will be ignored
2024-10-08 06:47:06,334 - root - WARNING - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-10-08 06:47:27,005 - root - INFO - got prompt
2024-10-08 06:47:27,558 - root - INFO - Using pytorch attention in VAE
2024-10-08 06:47:27,562 - root - INFO - Using pytorch attention in VAE
2024-10-08 06:47:32,035 - root - INFO - model weight dtype torch.bfloat16, manual cast: None
2024-10-08 06:47:32,037 - root - INFO - model_type FLUX
2024-10-08 06:51:05,456 - root - INFO - Requested to load FluxClipModel_
2024-10-08 06:51:05,826 - root - INFO - Loading 1 new model
2024-10-08 06:51:06,079 - root - INFO - loaded completely 0.0 4777.53759765625 True
2024-10-08 06:52:10,087 - root - WARNING - clip missing: ['text_projection.weight']
2024-10-08 06:53:16,881 - root - INFO - Loaded EVA02-CLIP-L-14-336 model config.
2024-10-08 06:53:21,695 - root - INFO - Shape of rope freq: torch.Size([576, 64])
2024-10-08 06:54:48,073 - root - INFO - Loading pretrained EVA02-CLIP-L-14-336 weights (eva_clip).
2024-10-08 06:56:15,114 - root - INFO - incompatible_keys.missing_keys: ['visual.rope.freqs_cos', 'visual.rope.freqs_sin', 'visual.blocks.0.attn.rope.freqs_cos', 'visual.blocks.0.attn.rope.freqs_sin', 'visual.blocks.1.attn.rope.freqs_cos', 'visual.blocks.1.attn.rope.freqs_sin', 'visual.blocks.2.attn.rope.freqs_cos', 'visual.blocks.2.attn.rope.freqs_sin', 'visual.blocks.3.attn.rope.freqs_cos', 'visual.blocks.3.attn.rope.freqs_sin', 'visual.blocks.4.attn.rope.freqs_cos', 'visual.blocks.4.attn.rope.freqs_sin', 'visual.blocks.5.attn.rope.freqs_cos', 'visual.blocks.5.attn.rope.freqs_sin', 'visual.blocks.6.attn.rope.freqs_cos', 'visual.blocks.6.attn.rope.freqs_sin', 'visual.blocks.7.attn.rope.freqs_cos', 'visual.blocks.7.attn.rope.freqs_sin', 'visual.blocks.8.attn.rope.freqs_cos', 'visual.blocks.8.attn.rope.freqs_sin', 'visual.blocks.9.attn.rope.freqs_cos', 'visual.blocks.9.attn.rope.freqs_sin', 'visual.blocks.10.attn.rope.freqs_cos', 'visual.blocks.10.attn.rope.freqs_sin', 'visual.blocks.11.attn.rope.freqs_cos', 'visual.blocks.11.attn.rope.freqs_sin', 'visual.blocks.12.attn.rope.freqs_cos', 'visual.blocks.12.attn.rope.freqs_sin', 'visual.blocks.13.attn.rope.freqs_cos', 'visual.blocks.13.attn.rope.freqs_sin', 'visual.blocks.14.attn.rope.freqs_cos', 'visual.blocks.14.attn.rope.freqs_sin', 'visual.blocks.15.attn.rope.freqs_cos', 'visual.blocks.15.attn.rope.freqs_sin', 'visual.blocks.16.attn.rope.freqs_cos', 'visual.blocks.16.attn.rope.freqs_sin', 'visual.blocks.17.attn.rope.freqs_cos', 'visual.blocks.17.attn.rope.freqs_sin', 'visual.blocks.18.attn.rope.freqs_cos', 'visual.blocks.18.attn.rope.freqs_sin', 'visual.blocks.19.attn.rope.freqs_cos', 'visual.blocks.19.attn.rope.freqs_sin', 'visual.blocks.20.attn.rope.freqs_cos', 'visual.blocks.20.attn.rope.freqs_sin', 'visual.blocks.21.attn.rope.freqs_cos', 'visual.blocks.21.attn.rope.freqs_sin', 'visual.blocks.22.attn.rope.freqs_cos', 'visual.blocks.22.attn.rope.freqs_sin', 'visual.blocks.23.attn.rope.freqs_cos', 'visual.blocks.23.attn.rope.freqs_sin']
2024-10-08 06:56:49,337 - root - INFO - Loading PuLID-Flux model.
2024-10-08 07:40:00,000 - root - ERROR - !!! Exception during processing !!! <urlopen error [Errno 110] Connection timed out>
2024-10-08 07:40:02,839 - root - ERROR - Traceback (most recent call last):
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ai/brx/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ai/brx/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ai/brx/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/ai/brx/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/ai/brx/ComfyUI/custom_nodes/ComfyUI-PuLID-Flux/pulidflux.py", line 282, in apply_pulid_flux
    face_helper = FaceRestoreHelper(
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/facexlib/utils/face_restoration_helper.py", line 103, in __init__
    self.face_parse = init_parsing_model(model_name='parsenet', device=self.device, model_rootpath=model_rootpath)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/facexlib/parsing/__init__.py", line 18, in init_parsing_model
    model_path = load_file_from_url(
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/facexlib/utils/misc.py", line 77, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/torch/hub.py", line 624, in download_url_to_file
    u = urlopen(req)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

2024-10-08 07:40:03,234 - root - INFO - Prompt executed in 3156.18 seconds
2024-10-08 07:54:37,089 - root - INFO - got prompt
2024-10-08 07:54:49,097 - root - ERROR - !!! Exception during processing !!! Remote end closed connection without response
2024-10-08 07:54:49,098 - root - ERROR - Traceback (most recent call last):
  File "/ai/brx/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ai/brx/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ai/brx/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/ai/brx/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/ai/brx/ComfyUI/custom_nodes/ComfyUI-PuLID-Flux/pulidflux.py", line 282, in apply_pulid_flux
    face_helper = FaceRestoreHelper(
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/facexlib/utils/face_restoration_helper.py", line 103, in __init__
    self.face_parse = init_parsing_model(model_name='parsenet', device=self.device, model_rootpath=model_rootpath)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/facexlib/parsing/__init__.py", line 18, in init_parsing_model
    model_path = load_file_from_url(
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/facexlib/utils/misc.py", line 77, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/torch/hub.py", line 624, in download_url_to_file
    u = urlopen(req)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

2024-10-08 07:54:49,100 - root - INFO - Prompt executed in 11.89 seconds
2024-10-08 07:56:06,309 - root - INFO - got prompt
2024-10-08 07:58:18,395 - root - ERROR - !!! Exception during processing !!! <urlopen error [Errno 110] Connection timed out>
2024-10-08 07:58:18,396 - root - ERROR - Traceback (most recent call last):
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ai/brx/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ai/brx/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ai/brx/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/ai/brx/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/ai/brx/ComfyUI/custom_nodes/ComfyUI-PuLID-Flux/pulidflux.py", line 282, in apply_pulid_flux
    face_helper = FaceRestoreHelper(
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/facexlib/utils/face_restoration_helper.py", line 103, in __init__
    self.face_parse = init_parsing_model(model_name='parsenet', device=self.device, model_rootpath=model_rootpath)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/facexlib/parsing/__init__.py", line 18, in init_parsing_model
    model_path = load_file_from_url(
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/facexlib/utils/misc.py", line 77, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/site-packages/torch/hub.py", line 624, in download_url_to_file
    u = urlopen(req)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/ai/miniconda3/envs/py310_comfyui/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

2024-10-08 07:58:18,398 - root - INFO - Prompt executed in 132.07 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":69,"last_link_id":137,"nodes":[{"id":50,"type":"PreviewImage","pos":{"0":2788,"1":-159},"size":{"0":841.524169921875,"1":698.3060302734375},"flags":{},"order":21,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":89,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":27,"type":"EmptySD3LatentImage","pos":{"0":1818,"1":708},"size":{"0":315,"1":106},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[86],"slot_index":0,"shape":3,"label":"Latent"}],"properties":{"Node name for S&R":"EmptySD3LatentImage"},"widgets_values":[768,1024,1],"color":"#323","bgcolor":"#535"},{"id":49,"type":"VAEDecode","pos":{"0":2558,"1":-64},"size":{"0":210,"1":46},"flags":{},"order":20,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":87,"label":"Latent"},{"name":"vae","type":"VAE","link":88,"label":"VAE"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[89],"slot_index":0,"shape":3,"label":"图像"}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":48,"type":"SamplerCustomAdvanced","pos":{"0":2111,"1":-30},"size":{"0":355.20001220703125,"1":326},"flags":{},"order":19,"mode":0,"inputs":[{"name":"noise","type":"NOISE","link":84,"label":"噪波生成"},{"name":"guider","type":"GUIDER","link":83,"label":"引导"},{"name":"sampler","type":"SAMPLER","link":85,"label":"采样器"},{"name":"sigmas","type":"SIGMAS","link":93,"label":"Sigmas"},{"name":"latent_image","type":"LATENT","link":86,"label":"Latent"}],"outputs":[{"name":"output","type":"LATENT","links":[87],"slot_index":0,"shape":3,"label":"输出"},{"name":"denoised_output","type":"LATENT","links":null,"shape":3,"label":"降噪输出"}],"properties":{"Node name for S&R":"SamplerCustomAdvanced"},"widgets_values":[]},{"id":26,"type":"FluxGuidance","pos":{"0":1759,"1":-79},"size":{"0":317.4000244140625,"1":58},"flags":{"collapsed":false},"order":15,"mode":0,"inputs":[{"name":"conditioning","type":"CONDITIONING","link":41,"label":"条件"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[107],"slot_index":0,"shape":3,"label":"条件"}],"properties":{"Node name for S&R":"FluxGuidance"},"widgets_values":[3.5],"color":"#233","bgcolor":"#355"},{"id":47,"type":"BasicGuider","pos":{"0":1786,"1":56},"size":{"0":241.79998779296875,"1":46},"flags":{},"order":18,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":122,"label":"模型"},{"name":"conditioning","type":"CONDITIONING","link":107,"label":"条件"}],"outputs":[{"name":"GUIDER","type":"GUIDER","links":[83],"slot_index":0,"shape":3,"label":"引导"}],"properties":{"Node name for S&R":"BasicGuider"},"widgets_values":[]},{"id":16,"type":"KSamplerSelect","pos":{"0":1769,"1":175},"size":{"0":315,"1":58},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"SAMPLER","type":"SAMPLER","links":[85],"slot_index":0,"shape":3,"label":"采样器"}],"properties":{"Node name for S&R":"KSamplerSelect"},"widgets_values":["euler"]},{"id":17,"type":"BasicScheduler","pos":{"0":1770,"1":279},"size":{"0":315,"1":106},"flags":{"collapsed":false},"order":16,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":133,"slot_index":0,"label":"模型"}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[93],"slot_index":0,"shape":3,"label":"Sigmas"}],"properties":{"Node name for S&R":"BasicScheduler"},"widgets_values":["simple",10,1]},{"id":67,"type":"Note","pos":{"0":376,"1":242},"size":{"0":367.06231689453125,"1":144.27279663085938},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[],"properties":{},"widgets_values":["a woman in dress\\(zhenzhu\\),feathers,Vanishing point composition,winkling stars,Full Length Shot,<lora:zhenzhudress flux 1024:1>,"],"color":"#432","bgcolor":"#653"},{"id":66,"type":"Reroute","pos":{"0":720,"1":-149},"size":[75,26],"flags":{},"order":14,"mode":0,"inputs":[{"name":"","type":"*","link":137}],"outputs":[{"name":"","type":"MODEL","links":[133,134],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":25,"type":"RandomNoise","pos":{"0":1769,"1":468},"size":{"0":315,"1":82},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"NOISE","type":"NOISE","links":[84],"slot_index":0,"shape":3,"label":"噪波生成"}],"properties":{"Node name for S&R":"RandomNoise"},"widgets_values":[221951571068804,"randomize"],"color":"#2a363b","bgcolor":"#3f5159"},{"id":6,"type":"CLIPTextEncode","pos":{"0":339,"1":26},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":13,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":132,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[41],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["a woman in dress\\(zhenzhu\\),feathers,Vanishing point composition,winkling stars,Full Length Shot,<lora:zhenzhudress flux 1024:1>,",true],"color":"#232","bgcolor":"#353"},{"id":10,"type":"VAELoader","pos":{"0":-114,"1":155},"size":{"0":311.81634521484375,"1":60.429901123046875},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[88],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["ae.sft"]},{"id":69,"type":"UnetLoaderGGUF","pos":{"0":-109,"1":-383},"size":{"0":315,"1":58},"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[],"slot_index":0,"shape":3,"label":"MODEL"}],"properties":{"Node name for S&R":"UnetLoaderGGUF"},"widgets_values":["Flux\\flux1-dev-Q5_1.gguf"]},{"id":63,"type":"UNETLoader","pos":{"0":-115,"1":-184},"size":{"0":315,"1":82},"flags":{},"order":6,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[136],"slot_index":0,"shape":3,"label":"模型"}],"properties":{"Node name for S&R":"UNETLoader"},"widgets_values":["flux1-dev-fp8.safetensors","default"]},{"id":68,"type":"LoraLoaderModelOnly","pos":{"0":336,"1":-161},"size":{"0":315,"1":82},"flags":{},"order":12,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":136,"label":"模型"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[137],"slot_index":0,"shape":3,"label":"模型"}],"properties":{"Node name for S&R":"LoraLoaderModelOnly"},"widgets_values":["Flux_小红书真实风格丨日常照片丨极致逼真_V1.safetensors",1]},{"id":54,"type":"LoadImage","pos":{"0":855,"1":484},"size":{"0":517.4287719726562,"1":440.54779052734375},"flags":{},"order":7,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[126],"slot_index":0,"shape":3,"label":"图像"},{"name":"MASK","type":"MASK","links":null,"shape":3,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["test_pose_control.jpg","image"]},{"id":64,"type":"DualCLIPLoader","pos":{"0":-115,"1":-43},"size":{"0":315,"1":106},"flags":{},"order":8,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[132],"slot_index":0,"shape":3,"label":"CLIP"}],"properties":{"Node name for S&R":"DualCLIPLoader"},"widgets_values":["t5xxl_fp8_e4m3fn.safetensors","clip_l.safetensors","flux"]},{"id":45,"type":"PulidFluxModelLoader","pos":{"0":876,"1":157},"size":{"0":315,"1":58},"flags":{},"order":9,"mode":0,"inputs":[],"outputs":[{"name":"PULIDFLUX","type":"PULIDFLUX","links":[125],"slot_index":0,"shape":3,"label":"PULIDFLUX"}],"properties":{"Node name for S&R":"PulidFluxModelLoader"},"widgets_values":["pulid_flux_v0.9.0.safetensors"]},{"id":51,"type":"PulidFluxEvaClipLoader","pos":{"0":898,"1":-71},"size":{"0":327.5999755859375,"1":26},"flags":{},"order":10,"mode":0,"inputs":[],"outputs":[{"name":"EVA_CLIP","type":"EVA_CLIP","links":[123],"slot_index":0,"shape":3,"label":"EVA_CLIP"}],"properties":{"Node name for S&R":"PulidFluxEvaClipLoader"},"widgets_values":[]},{"id":53,"type":"PulidFluxInsightFaceLoader","pos":{"0":888,"1":10},"size":{"0":365.4000244140625,"1":58},"flags":{},"order":11,"mode":0,"inputs":[],"outputs":[{"name":"FACEANALYSIS","type":"FACEANALYSIS","links":[124],"slot_index":0,"shape":3,"label":"FACEANALYSIS"}],"properties":{"Node name for S&R":"PulidFluxInsightFaceLoader"},"widgets_values":["CUDA"]},{"id":62,"type":"ApplyPulidFlux","pos":{"0":1276,"1":-50},"size":{"0":315,"1":206},"flags":{},"order":17,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":134,"label":"model"},{"name":"pulid_flux","type":"PULIDFLUX","link":125,"label":"pulid_flux"},{"name":"eva_clip","type":"EVA_CLIP","link":123,"label":"eva_clip"},{"name":"face_analysis","type":"FACEANALYSIS","link":124,"label":"face_analysis"},{"name":"image","type":"IMAGE","link":126,"label":"image"},{"name":"attn_mask","type":"MASK","link":null,"label":"attn_mask"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[122],"slot_index":0,"shape":3,"label":"MODEL"}],"properties":{"Node name for S&R":"ApplyPulidFlux"},"widgets_values":[1,0,1]}],"links":[[41,6,0,26,0,"CONDITIONING"],[83,47,0,48,1,"GUIDER"],[84,25,0,48,0,"NOISE"],[85,16,0,48,2,"SAMPLER"],[86,27,0,48,4,"LATENT"],[87,48,0,49,0,"LATENT"],[88,10,0,49,1,"VAE"],[89,49,0,50,0,"IMAGE"],[93,17,0,48,3,"SIGMAS"],[107,26,0,47,1,"CONDITIONING"],[122,62,0,47,0,"MODEL"],[123,51,0,62,2,"EVA_CLIP"],[124,53,0,62,3,"FACEANALYSIS"],[125,45,0,62,1,"PULIDFLUX"],[126,54,0,62,4,"IMAGE"],[132,64,0,6,0,"CLIP"],[133,66,0,17,0,"MODEL"],[134,66,0,62,0,"MODEL"],[136,63,0,68,0,"MODEL"],[137,68,0,66,0,"*"]],"groups":[{"title":"Flux PuLID  人物一致性 工作流 楚门的AI世界","bounding":[291,-519,3136,186],"color":"#3f789e","font_size":150,"flags":{}},{"title":"模型加载","bounding":[-120,-264,342,524],"color":"#3f789e","font_size":24,"flags":{}},{"title":"PuLID Flux","bounding":[872,-153,747,387],"color":"#3f789e","font_size":24,"flags":{}},{"title":"采样器","bounding":[1685,-175,847,754],"color":"#3f789e","font_size":24,"flags":{}},{"title":"GGUF模型加载","bounding":[-119,-469,335,166],"color":"#3f789e","font_size":24,"flags":{}},{"title":"lora","bounding":[311,-261,372,197],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":1.1671841070450009,"offset":[-608.0911053997992,267.60094161203955]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by VCasecnikovs** [comment]
Have the same right now

**Comment by cubiq** [comment]
that looks like a connection error white trying to download something
