### ISSUE TITLE
Error: PulidInsightFaceLoader

### ISSUE THREAD

**Issue by ffdff123** [cubiq/PuLID_ComfyUI#88]
# ComfyUI Error Report
## Error Details
- **Node Type:** PulidInsightFaceLoader
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace
```
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\PuLID_ComfyUI\pulid.py", line 240, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l

  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models

```
## System Information
- **ComfyUI Version:** v0.2.2-101-g5f9d5a2
- **Arguments:** E:\01StableDiffusion\ComfyUI-aki-v1.4\main.py --port 8187 --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 22678808568
  - **Torch VRAM Total:** 1711276032
  - **Torch VRAM Free:** 41101304

## Logs
```
2024-10-16 00:05:31,274 - root - INFO - Total VRAM 24564 MB, total RAM 65306 MB
2024-10-16 00:05:31,274 - root - INFO - pytorch version: 2.3.1+cu121
2024-10-16 00:05:32,208 - root - INFO - xformers version: 0.0.27
2024-10-16 00:05:32,209 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-16 00:05:32,209 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 Ti : cudaMallocAsync
2024-10-16 00:05:32,385 - root - INFO - Using xformers cross attention
2024-10-16 00:05:33,092 - root - INFO - [Prompt Server] web root: E:\01StableDiffusion\ComfyUI-aki-v1.4\web
2024-10-16 00:05:42,439 - root - INFO - Total VRAM 24564 MB, total RAM 65306 MB
2024-10-16 00:05:42,439 - root - INFO - pytorch version: 2.3.1+cu121
2024-10-16 00:05:42,440 - root - INFO - xformers version: 0.0.27
2024-10-16 00:05:42,440 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-16 00:05:42,440 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 Ti : cudaMallocAsync
2024-10-16 00:05:44,816 - root - INFO - --------------
2024-10-16 00:05:44,816 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-10-16 00:05:44,816 - root - INFO - ChatGPT.available True
2024-10-16 00:05:44,817 - root - INFO - edit_mask.available True
2024-10-16 00:05:45,057 - root - INFO - ClipInterrogator.available True
2024-10-16 00:05:45,059 - root - INFO - PromptGenerate.available True
2024-10-16 00:05:45,059 - root - INFO - ChinesePrompt.available True
2024-10-16 00:05:45,059 - root - INFO - RembgNode_.available True
2024-10-16 00:05:45,963 - root - INFO - TripoSR.available
2024-10-16 00:05:45,964 - root - INFO - MiniCPMNode.available
2024-10-16 00:05:46,200 - root - INFO - Scenedetect.available
2024-10-16 00:05:46,347 - root - INFO - FishSpeech.available
2024-10-16 00:05:46,351 - root - INFO - SenseVoice.available False
2024-10-16 00:05:46,351 - root - INFO - [93m -------------- [0m
2024-10-16 00:05:51,224 - root - WARNING - Traceback (most recent call last):
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\facerestore_cf-master\__init__.py", line 8, in <module>
    from custom_nodes.facerestore_cf.facelib.utils.face_restoration_helper import FaceRestoreHelper
ModuleNotFoundError: No module named 'custom_nodes.facerestore_cf'

2024-10-16 00:05:51,225 - root - WARNING - Cannot import E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\facerestore_cf-master module for custom nodes: No module named 'custom_nodes.facerestore_cf'
2024-10-16 00:05:56,523 - root - INFO - 
Import times for custom nodes:
2024-10-16 00:05:56,523 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\websocket_image_save.py
2024-10-16 00:05:56,523 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-10-16 00:05:56,524 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\sdxl_prompt_styler
2024-10-16 00:05:56,524 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ControlNet-LLLite-ComfyUI
2024-10-16 00:05:56,524 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Inpaint-CropAndStitch
2024-10-16 00:05:56,524 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\FreeU_Advanced
2024-10-16 00:05:56,525 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Eagle-PNGInfo
2024-10-16 00:05:56,525 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-BRIA_AI-RMBG
2024-10-16 00:05:56,525 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_TiledKSampler
2024-10-16 00:05:56,525 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-10-16 00:05:56,526 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\stability-ComfyUI-nodes
2024-10-16 00:05:56,526 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\cg-use-everywhere
2024-10-16 00:05:56,526 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-16 00:05:56,526 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\efficiency-nodes-comfyui
2024-10-16 00:05:56,526 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\cg-image-picker
2024-10-16 00:05:56,526 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\masquerade-nodes-comfyui
2024-10-16 00:05:56,526 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyLiterals
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-post-processing-nodes
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-enricos-nodes
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_experiments
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\comfyui_controlnet_aux
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\PowerNoiseSuite
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\images-grid-comfy-plugin
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Text_Image-Composite
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\comfy-image-saver
2024-10-16 00:05:56,527 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Custom-Scripts
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_essentials-main
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyMath
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds (IMPORT FAILED): E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\facerestore_cf-master
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Impact-Pack
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\rgthree-comfy
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\x-flux-comfyui
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\comfyui-ollama
2024-10-16 00:05:56,528 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-KJNodes
2024-10-16 00:05:56,529 - root - INFO -    0.0 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-16 00:05:56,529 - root - INFO -    0.1 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\comfyui-workspace-manager
2024-10-16 00:05:56,529 - root - INFO -    0.1 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-10-16 00:05:56,529 - root - INFO -    0.1 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_InstantID-main
2024-10-16 00:05:56,529 - root - INFO -    0.1 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Inspire-Pack
2024-10-16 00:05:56,529 - root - INFO -    0.1 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Crystools
2024-10-16 00:05:56,529 - root - INFO -    0.1 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MingNodes
2024-10-16 00:05:56,529 - root - INFO -    0.1 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\PuLID_ComfyUI
2024-10-16 00:05:56,529 - root - INFO -    0.1 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Marigold
2024-10-16 00:05:56,529 - root - INFO -    0.2 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\comfyui_segment_anything-main
2024-10-16 00:05:56,529 - root - INFO -    0.2 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_LayerStyle
2024-10-16 00:05:56,529 - root - INFO -    0.2 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\comfyui-reactor-node
2024-10-16 00:05:56,530 - root - INFO -    0.3 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\comfyui-dynamicprompts
2024-10-16 00:05:56,530 - root - INFO -    0.4 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager
2024-10-16 00:05:56,530 - root - INFO -    0.4 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_FizzNodes
2024-10-16 00:05:56,530 - root - INFO -    0.4 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Gemini
2024-10-16 00:05:56,530 - root - INFO -    0.7 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\a-person-mask-generator
2024-10-16 00:05:56,530 - root - INFO -    0.8 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Easy-Use
2024-10-16 00:05:56,530 - root - INFO -    1.2 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\comfyui-art-venture
2024-10-16 00:05:56,530 - root - INFO -    3.2 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\comfyui-mixlab-nodes
2024-10-16 00:05:56,530 - root - INFO -    3.6 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-10-16 00:05:56,530 - root - INFO -    4.5 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Inspyrenet-Rembg
2024-10-16 00:05:56,530 - root - INFO -    5.1 seconds: E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\was-node-suite-comfyui
2024-10-16 00:05:56,530 - root - INFO - 
2024-10-16 00:05:56,557 - root - INFO - Starting server

2024-10-16 00:05:56,557 - root - INFO - To see the GUI go to: http://127.0.0.1:8187
2024-10-16 00:06:43,078 - httpx - INFO - HTTP Request: GET http://127.0.0.1:11434/api/tags "HTTP/1.1 200 OK"
2024-10-16 00:06:43,110 - httpx - INFO - HTTP Request: GET http://127.0.0.1:11434/api/tags "HTTP/1.1 200 OK"
2024-10-16 00:10:53,410 - root - INFO - got prompt
2024-10-16 00:10:54,354 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-16 00:10:54,357 - root - INFO - model_type EPS
2024-10-16 00:10:55,661 - root - INFO - Using xformers attention in VAE
2024-10-16 00:10:55,663 - root - INFO - Using xformers attention in VAE
2024-10-16 00:10:56,284 - root - INFO - Requested to load SDXLClipModel
2024-10-16 00:10:56,284 - root - INFO - Loading 1 new model
2024-10-16 00:10:56,301 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-16 00:10:58,465 - root - INFO - Requested to load SDXLClipModel
2024-10-16 00:10:58,465 - root - INFO - Loading 1 new model
2024-10-16 00:11:04,255 - httpx - INFO - HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
2024-10-16 00:11:06,027 - httpx - INFO - HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
2024-10-16 00:11:06,185 - root - ERROR - !!! Exception during processing !!! 
2024-10-16 00:11:06,187 - root - ERROR - Traceback (most recent call last):
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\PuLID_ComfyUI\pulid.py", line 240, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

2024-10-16 00:11:06,188 - root - INFO - Prompt executed in 12.47 seconds
2024-10-16 00:22:21,137 - root - INFO - got prompt
2024-10-16 00:22:21,471 - root - ERROR - !!! Exception during processing !!! 
2024-10-16 00:22:21,472 - root - ERROR - Traceback (most recent call last):
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\PuLID_ComfyUI\pulid.py", line 240, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

2024-10-16 00:22:21,474 - root - INFO - Prompt executed in 0.05 seconds
2024-10-16 00:22:26,455 - root - INFO - got prompt
2024-10-16 00:22:26,772 - root - ERROR - !!! Exception during processing !!! 
2024-10-16 00:22:26,773 - root - ERROR - Traceback (most recent call last):
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\PuLID_ComfyUI\pulid.py", line 240, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

2024-10-16 00:22:26,776 - root - INFO - Prompt executed in 0.05 seconds
2024-10-16 00:22:31,730 - root - INFO - got prompt
2024-10-16 00:22:32,011 - root - ERROR - !!! Exception during processing !!! 
2024-10-16 00:22:32,013 - root - ERROR - Traceback (most recent call last):
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\custom_nodes\PuLID_ComfyUI\pulid.py", line 240, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
  File "E:\01StableDiffusion\ComfyUI-aki-v1.4\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

2024-10-16 00:22:32,015 - root - INFO - Prompt executed in 0.05 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by dm-v-klim** [comment]
Change path from ComfyUI\models\insightface\models\antelopev2\antelopev2 to ComfyUI\models\insightface\models\antelopev2\ its work for me.

**Comment by Hunt3rseeker** [comment]
> Change path from ComfyUI\models\insightface\models\antelopev2\antelopev2 to ComfyUI\models\insightface\models\antelopev2 its work for me.

What do you mean exactly with "change path"? I have the same paths available as you, but I'm not sure what to change and where

**Comment by banini1841** [comment]
Have you found a solution? I have exactly the same error message. My Comfyui worked an then, without doing anything (updates, ...) I got this error. Reinstalling comfyUI also didn't help.

**Comment by banini1841** [comment]
my antelope is already in the correct folder so that doesent solve it

**Comment by motoyagugu** [comment]
@[eshantsingh007](https://github.com/eshantsingh007) eshantsingh007 mentioned this issue [3 weeks ago](https://github.com/cubiq/PuLID_ComfyUI/issues/88#ref-issue-2731125978)
https://github.com/cubiq/PuLID_ComfyUI/issues/118

Solved!
